apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a
spec:
  template:
    metadata:
      annotations:
        sidecar.opentelemetry.io/inject: "true"
        instrumentation.opentelemetry.io/inject-java: "true"
