apiVersion: v1
kind: Secret
metadata:
  name: s3-bucket
  namespace: tempostack
stringData:
  endpoint: http://s3.openshift-storage.svc
  bucket: "tempostorage"
  access_key_id: ${AWS_ACCESS_KEY_ID}
  access_key_secret: ${AWS_SECRET_ACCESS_KEY}
type: Opaque
---
apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: tempostack
  namespace: tempostack
spec:
  storageSize: 1Gi
  storage:
    secret:
      name: s3-bucket
      type: s3
    tls:
      enabled: false
  resources:
    total:
      limits:
        memory: 2Gi
        cpu: 2000m
  template:
    queryFrontend:
      jaegerQuery:
        enabled: true
        ingress:
          route:
            termination: edge
          type: route
